WebAppPeliculas/WebAppPeliculas/Controllers/ActoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebAppPeliculas.Models.Entity;
using WebAppPeliculas.Servicies;

namespace WebAppPeliculas.Controllers
{
    public class ActoresController : Controller
    {
        private string usuario = "";
        private string tokenAccess = "";
        ActualHost actualHost = new ActualHost();

        public IActionResult Index()
        {
            IEnumerable<ActorEntity> lstActor = null;
            try
            {

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(actualHost.HostNameActual + "Actores/ListadoActoresPublico");
                    var responseTask = client.GetAsync("ListadoActoresPublico");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readJob = result.Content.ReadAsAsync<IList<ActorEntity>>();
                        readJob.Wait();
                        lstActor = readJob.Result;
                    }
                    else
                    {
                        lstActor = Enumerable.Empty<ActorEntity>();

                    }


                }

                return View(lstActor);
            }
            catch (Exception)
            {

                lstActor = Enumerable.Empty<ActorEntity>();
                return View(lstActor);
            }
        }

        public IActionResult ListadoActores()
        {
            IEnumerable<ActorEntity> lstActor = null;
            try
            {
                if (Validacion() == false)
                {
                    return RedirectToAction("Login", "Usuario");
                }

                using (var client = new HttpClient())
                {
                    string cookieToken = Request.Cookies["ACCESS_TOKEN_PELIS"];
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", cookieToken);
                    client.BaseAddress = new Uri(actualHost.HostNameActual + "Actores/ListadoActores");
                    var responseTask = client.GetAsync("ListadoActores");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readJob = result.Content.ReadAsAsync<IList<ActorEntity>>();
                        readJob.Wait();
                        lstActor = readJob.Result;
                    }
                    else
                    {
                        lstActor = Enumerable.Empty<ActorEntity>();

                    }


                }

                return View(lstActor);
            }
            catch (Exception)
            {

                lstActor = Enumerable.Empty<ActorEntity>();
                return View(lstActor);
            }


        }

        [HttpGet]
        public IActionResult GuardarActor()
        {
            if (Validacion() == false)
            {
                return RedirectToAction("Login", "Usuario");
            }
            return View();

        }

        [HttpPost]
        public IActionResult GuardarActor(ActorEntity actor)
        {
            try
            {
                if (Validacion() == false)
                {
                    return RedirectToAction("Login", "Usuario");
                }
                using (var client = new HttpClient())
                {
                    string cookieToken = Request.Cookies["ACCESS_TOKEN_PELIS"];
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", cookieToken);
                    client.BaseAddress = new Uri(actualHost.HostNameActual + "Actores/GuardarActor");
                    var postJob = client.PostAsJsonAsync<ActorEntity>("GuardarActor", actor);
                    postJob.Wait();

                    var postResult = postJob.Result;
                    if (postResult.IsSuccessStatusCode)
                    {
                        return RedirectToAction("ListadoActores");
                    }
                    else
                    {
                        return View();
                    }

                }

            }
            catch (Exception)
            {

                return View();
            }


        }

        [HttpGet]
        public IActionResult EditarActor(int id)
        {
            try
            {
                if (Validacion() == false)
                {
                    return RedirectToAction("Login", "Usuario");
                }
                if (id.ToString() == "" || id.ToString() == null)
                {
                    return View();
                }

                using (var client = new HttpClient())
                {
                    ActorEntity Actor = null;
                    string cookieToken = Request.Cookies["ACCESS_TOKEN_PELIS"];
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", cookieToken);
                    client.BaseAddress = new Uri(actualHost.HostNameActual + "Actores/");
                    var responseTask = client.GetAsync("BuscarActor/" + id.ToString());
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        result.StatusCode = System.Net.HttpStatusCode.OK;
                        var readTask = result.Content.ReadAsAsync<ActorEntity>();
                        readTask.Wait();

                        Actor = readTask.Result;

                        if (result.StatusCode == System.Net.HttpStatusCode.OK)
                        {
                            return View(Actor);
                        }
                        else
                        {
                            return View();
                        }
                    }
                    else
                    {
                        return View();
                    }
                }
            }
            catch (Exception)
            {
                return View();
            }


        }

        [HttpPost]
        public IActionResult EditarActor(ActorEntity actor)
        {
            try
            {
                if (Validacion() == false)
                {
                    return RedirectToAction("Login", "Usuario");
                }
                using (var client = new HttpClient())
                {
                    string cookieToken = Request.Cookies["ACCESS_TOKEN_PELIS"];
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", cookieToken);
                    client.BaseAddress = new Uri(actualHost.HostNameActual + "Actores/EditarActor");
                    var putTaks = client.PutAsJsonAsync<ActorEntity>("EditarActor", actor);
                    putTaks.Wait();

                    var result = putTaks.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return View();
                    }
                    else
                    {
                        return View();
                    }


                }
            }
            catch (Exception)
            {
                return View();
            }

        }

        [HttpGet]
        public IActionResult EliminarActor(int id)
        {
            try
            {
                if (Validacion() == false)
                {
                    return RedirectToAction("Login", "Usuario");
                }
                if (id.ToString() == "" || id.ToString() == null)
                {
                    return View();
                }

                using (var client = new HttpClient())
                {
                    ActorEntity actor = null;
                    string cookieToken = Request.Cookies["ACCESS_TOKEN_PELIS"];
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", cookieToken);
                    client.BaseAddress = new Uri(actualHost.HostNameActual + "Actores/");
                    var responseTask = client.GetAsync("BuscarActor/" + id.ToString());
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        result.StatusCode = System.Net.HttpStatusCode.OK;
                        var readTask = result.Content.ReadAsAsync<ActorEntity>();
                        readTask.Wait();

                        actor = readTask.Result;

                        if (result.StatusCode == System.Net.HttpStatusCode.OK)
                        {
                            return View(actor);
                        }
                        else
                        {
                            return View();
                        }
                    }
                    else
                    {
                        return View();
                    }
                }
            }
            catch (Exception)
            {
                return View();
            }


        }

        [HttpPost]
        public IActionResult EliminarActor(int id, IFormCollection formCollection)
        {
            try
            {
                if (Validacion() == false)
                {
                    return RedirectToAction("Login", "Usuario");
                }
                using (var client = new HttpClient())
                {
                    string cookieToken = Request.Cookies["ACCESS_TOKEN_PELIS"];

WebAppPeliculas/WebAppPeliculas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppPeliculas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/twitter-bootstrap/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppPeliculas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Peliculas" asp-action="Index">Peliculas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actores" asp-action="Index">Actores</a>
                        </li>
                        <li class="nav-item" id="liGestionarLink">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Gestionar" id="gestionarLink"></a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login" id="loginLink">Iniciar Sesion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebAppPeliculas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Estado.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>